<template lang="pug">
div(offscreen="~")
  div(text="mc-yellow" color="mc-yellow")
  div(text="mc-blue" color="mc-blue")
  div(text="mc-orange" color="mc-orange")
  div(text="mc-black" color="mc-black")
  div(text="mc-black-rgb" color="mc-black-rgb")
  div(text="mc-white" color="white")
  div(text="mc-red" color="mc-red")
  div(text="mc-gray" color="mc-gray")
  div(text="mc-gray-400" color="mc-gray-400")
  div(text="mc-gray_light" color="mc-gray.light")
  div(text="mc-gws" color="mc-gws")
  div(text="mc-astro_credit" color="mc-astro_credit")
  div(text="mc-green" color="green")
  div(text="mc-purple" color="purple")
  div(text="mc-gold" color="gold")
  div(text="mc-white_10" color="white_10")
  div(text="mc-white_20" color="white_20")
  div(text="mc-white_40" color="white_40")
  div(text="mc-white_60" color="white_60")
  div(text="mc-white_80" color="white_80")
  div(text="mc-mint" color="mc-mint")
  div(text="mc-mint_20" color="mc-mint_20")
  div(text="mc-mint_40" color="mc-mint_40")
  div(text="mc-success" color="mc-success")
  div(text="mc-whitenew" color="mc-whitenew")
  div(text="mc-warning" color="mc-warning")
  div(text="mc-arcade" color="mc-arcade")
  div(text="mc-gravity-grade", color="mc-gravity-grade")

  div(fill="mc-gravity-grade" color="mc-gravity-grade")
  div(fill="mc-arcade" color="mc-arcade")
  div(fill="mc-gray_light" color="mc-gray_light")
  div(fill="mc-yellow" color="mc-yellow")
  div(fill="mc-red" color="mc-red")
  div(fill="mc-ygreen" color="mc-ygreen")
  div(fill="mc-success" color="mc-success")
  div(fill="white" color="white")
  div(fill="mc-whitenew" color="mc-whitenew")
  div(fill="mc-warning" color="mc-warning")
  div(fill="tier-blue" color="tier-blue")
  div(fill="tier-gold" color="tier-gold")
  div(fill="tier-purple" color="tier-purple")
  div(fill="tier-blue" color="tier-blue")
  div(fill="tier-green" color="tier-green")
  div(fill="tier-white" color="tier-white")
  div(fill="tier-orange" color="tier-orange")

  //- div(bg="[url(~/assets/images/lobby/entry/netempire-bg.png)]")
  //- div(bg="[url(~/assets/images/lobby/entry/mc-bg.png)]")

  div(ring="mc-gravity-grade")
  div(ring="mc-arcade")
  div(ring="mc-yellow")
  div(ring="mc-blue")
  div(ring="mc-orange")
  div(ring="mc-orange_20")
  div(ring="white")
  div(ring="mc-mint")
  div(ring="mc-mint_20")
  div(ring="mc-mint_40")
  div(ring="mc-warning")

  div(mc-ring="color-mc-orange 1 hover-2 static-2")
  div(mc-ring="color-mc-mint static-2")

  div(text-shadow="mc-gravity-grade")
  div(text-shadow="mc-arcade")
  div(text-shadow="mc-yellow")
  div(text-shadow="mc-blue")
  div(text-shadow="mc-orange")
  div(text-shadow="white")
  div(text-shadow="mc-mint")
  div(text-shadow="mc-red")
  div(text-shadow="mc-ygreen")
  div(text-shadow="mc-whitenew")
  div(text-shadow="mc-warning")

  div(bg="mc-gravity-grade")
  div(bg="mc-arcade")
  div(bg="mc-yellow")
  div(bg="mc-blue")
  div(bg="mc-orange")
  div(bg="mc-orange_10")
  div(bg="mc-orange_20")
  div(bg="mc-orange_40")
  div(bg="mc-orange_60")
  div(bg="white")
  div(bg="mc-mint")
  div(bg="mc-mint_10")
  div(bg="mc-mint_20")
  div(bg="mc-mint_40")
  div(bg="mc-mint_60")
  div(bg="mc-black")
  div(bg="mc-black_20")
  div(bg="mc-red")
  div(bg="mc-gray_light")
  div(bg="mc-ygreen_40")
  div(bg="mc-gray")
  div(bg="mc-whitenew")
  div(bg="mc-warning")

  div(bg="tier-gold")
  div(bg="tier-purple")
  div(bg="tier-blue")
  div(bg="tier-green")
  div(bg="tier-white")
  div(bg="tier-orange")

  div(text="tier-gold")
  div(text="tier-purple")
  div(text="tier-blue")
  div(text="tier-green")
  div(text="tier-white")
  div(text="tier-orange")
  div(text="mc-black")

  div(color="tier-gold")
  div(color="tier-purple")
  div(color="tier-blue")
  div(color="tier-green")
  div(color="tier-white")
  div(color="tier-orange")
  div(color="mc-gray_light")
  div(color="mc-black")
  div(color="mc-warning")

  div(color="condition-success")
  div(color="condition-yellow")
  div(color="condition-red")

  div(text="condition-success")
  div(text="condition-yellow")
  div(text="condition-red")

  div(border="mc-orange_40")
  div(b="tier-gold")
  div(b="tier-purple")
  div(b="tier-blue")
  div(b="tier-green")
  div(b="tier-white")

  //-for creating white outlines to svg's
  svg(xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" width="0" height="0")
    filter(id="white-outline")
      feMorphology(in="SourceAlpha" result="expanded" operator="dilate" radius="0.5")
      feFlood(flood-color="white" flood-opacity="0.8")
      feComposite(in2="expanded" operator="in")
      feComposite(in="SourceGraphic")
</template>